# Generated by Django 5.2.3 on 2025-06-22 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedEHRTextData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id_on_rs', models.CharField(db_index=True, max_length=100, verbose_name='Mã Bệnh Nhân (trên RS)')),
                ('created_by_ac_user_id', models.IntegerField(db_index=True, verbose_name='Người Tạo (ID từ Auth Center)')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô Tả Chung')),
                ('data_type', models.CharField(blank=True, help_text='Ví dụ: CONSULTATION_NOTE, LAB_RESULT_SUMMARY', max_length=100, null=True, verbose_name='Loại Dữ Liệu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày Cập Nhật')),
                ('cpabe_policy_applied', models.TextField(verbose_name='Chính sách CP-ABE đã áp dụng cho KEK')),
                ('encrypted_kek_b64', models.TextField(verbose_name='KEK đã mã hóa CP-ABE (Base64)')),
                ('aes_iv_b64', models.CharField(max_length=24, verbose_name='AES IV (Base64)')),
                ('encrypted_main_content_b64', models.TextField(verbose_name='Nội dung chính đã mã hóa AES (Base64)')),
            ],
            options={
                'verbose_name': 'Dữ Liệu EHR Văn Bản Đã Mã Hóa',
                'verbose_name_plural': 'Các Dữ Liệu EHR Văn Bản Đã Mã Hóa',
                'ordering': ['-created_at'],
            },
        ),
    ]
