# Generated by Django 5.2.1 on 2025-05-31 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên gợi nhớ cho chính sách', max_length=255, unique=True)),
                ('policy_definition', models.TextField(help_text='Chuỗi định nghĩa chính sách theo cú pháp của thư viện CP-ABE')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chính sách Truy cập',
                'verbose_name_plural': 'Các Chính sách Truy cập',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tên thuộc tính, ví dụ: 'Researcher'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thuộc tính',
                'verbose_name_plural': 'Các Thuộc tính',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abe_encrypted_aes_key_blob', models.BinaryField(help_text='Khóa AES (đã được client mã hóa bằng CP-ABE theo chính sách đã chọn)')),
                ('aes_iv_for_content', models.BinaryField(help_text='IV được client sử dụng cho mã hóa AES-GCM của nội dung file')),
                ('encrypted_content_blob', models.BinaryField(help_text='Nội dung file đã được client mã hóa bằng AES-GCM (có thể đã bao gồm auth tag)')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, help_text='Người dùng đã tải lên và mã hóa dữ liệu này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_data', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(help_text='Chính sách truy cập mà client đã sử dụng để mã hóa khóa AES bằng CP-ABE', on_delete=django.db.models.deletion.PROTECT, related_name='client_encrypted_data_items', to='backend.accesspolicy')),
            ],
            options={
                'verbose_name': 'Dữ liệu Mã hóa Phía Client',
                'verbose_name_plural': 'Các Dữ liệu Mã hóa Phía Client',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_attribute', to='backend.attribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_possessed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thuộc tính Người dùng',
                'verbose_name_plural': 'Các Thuộc tính Người dùng',
                'unique_together': {('user', 'attribute')},
            },
        ),
    ]
