# Generated by Django 5.2.1 on 2025-06-01 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên gợi nhớ cho policy template', max_length=255, unique=True)),
                ('policy_template', models.TextField(help_text='Template chính sách với placeholder {{PATIENT_ID}}, {{HOSPITAL_ID}}, etc.')),
                ('policy_type', models.CharField(choices=[('static', 'Chính sách tĩnh - không cần patient_id'), ('patient_specific', 'Chính sách theo bệnh nhân - cần patient_id'), ('dynamic', 'Chính sách động - có thể có nhiều placeholder')], default='static', help_text='Loại chính sách', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về chính sách này', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chính sách truy cập',
                'verbose_name_plural': 'Chính sách truy cập',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tên thuộc tính, ví dụ: 'doctor', 'family_member'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về thuộc tính này', null=True)),
                ('supports_patient_id', models.BooleanField(default=False, help_text='Có hỗ trợ patient_id không? (chỉ family_member = True)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thuộc tính',
                'verbose_name_plural': 'Thuộc tính',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Email đăng nhập, phải unique', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Tên', max_length=30)),
                ('last_name', models.CharField(blank=True, help_text='Họ', max_length=30)),
                ('patient_id', models.CharField(db_index=True, editable=False, help_text='ID bệnh nhân duy nhất, tự động tạo khi đăng ký', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='ProtectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_patient_id', models.CharField(blank=True, help_text='Patient ID mà dữ liệu này thuộc về (cho patient-specific policies)', max_length=50, null=True)),
                ('rendered_policy', models.TextField(help_text='Policy đã được render với patient_id cụ thể (cache để tối ưu)')),
                ('abe_encrypted_aes_key_blob', models.BinaryField(help_text='AES key đã được mã hóa bằng CP-ABE (client thực hiện)')),
                ('aes_iv_for_content', models.BinaryField(help_text='IV được sử dụng cho AES-GCM encryption của nội dung')),
                ('encrypted_content_blob', models.BinaryField(help_text='Nội dung file đã được mã hóa bằng AES-GCM (client thực hiện)')),
                ('filename', models.CharField(blank=True, help_text='Tên file gốc', max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type của file', max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Kích thước file gốc (bytes)', null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả về file này', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, help_text='User đã upload và mã hóa dữ liệu này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_data', to=settings.AUTH_USER_MODEL)),
                ('policy_template', models.ForeignKey(help_text='Template chính sách được sử dụng', on_delete=django.db.models.deletion.PROTECT, related_name='protected_data_items', to='backend.accesspolicy')),
            ],
            options={
                'verbose_name': 'Dữ liệu được bảo vệ',
                'verbose_name_plural': 'Dữ liệu được bảo vệ',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['target_patient_id'], name='backend_pro_target__d25bfe_idx'), models.Index(fields=['policy_template', 'target_patient_id'], name='backend_pro_policy__83b099_idx'), models.Index(fields=['owner_user', 'uploaded_at'], name='backend_pro_owner_u_a1e1ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, help_text='Patient ID cụ thể (chỉ dành cho family_member)', max_length=50, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(help_text='Loại attribute', on_delete=django.db.models.deletion.CASCADE, related_name='users_with_attribute', to='backend.attribute')),
                ('user', models.ForeignKey(help_text='User sở hữu attribute này', on_delete=django.db.models.deletion.CASCADE, related_name='attributes_possessed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thuộc tính người dùng',
                'verbose_name_plural': 'Thuộc tính người dùng',
                'indexes': [models.Index(fields=['user', 'attribute'], name='backend_use_user_id_1cf67b_idx'), models.Index(fields=['patient_id'], name='backend_use_patient_9f2316_idx'), models.Index(fields=['attribute', 'patient_id'], name='backend_use_attribu_55db48_idx')],
                'unique_together': {('user', 'attribute', 'patient_id')},
            },
        ),
    ]
