# Generated by Django 5.2.1 on 2025-06-08 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên gợi nhớ cho policy', max_length=255, unique=True)),
                ('policy_template', models.TextField(help_text="Static policy string, ví dụ: 'doctor OR (hospital_1 AND nurse)'")),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về chính sách này', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chính sách truy cập',
                'verbose_name_plural': 'Chính sách truy cập',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tên thuộc tính static, ví dụ: 'doctor', 'nurse'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về thuộc tính này', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thuộc tính',
                'verbose_name_plural': 'Thuộc tính',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Email đăng nhập', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Tên', max_length=30)),
                ('last_name', models.CharField(blank=True, help_text='Họ', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, help_text='Mã số bệnh nhân (không mã hóa) để phân biệt các hồ sơ', max_length=50, null=True)),
                ('patient_name_blob', models.BinaryField(blank=True, help_text='Họ tên bệnh nhân đã mã hóa', null=True)),
                ('patient_age_blob', models.BinaryField(blank=True, help_text='Tuổi bệnh nhân đã mã hóa', null=True)),
                ('patient_gender_blob', models.BinaryField(blank=True, help_text='Giới tính bệnh nhân đã mã hóa', null=True)),
                ('patient_phone_blob', models.BinaryField(blank=True, help_text='Số điện thoại bệnh nhân đã mã hóa', null=True)),
                ('patient_info_aes_key_blob', models.BinaryField(help_text='AES key cho thông tin bệnh nhân, đã mã hóa bằng CP-ABE Waters11')),
                ('patient_info_aes_iv_blob', models.BinaryField(help_text='IV cho AES-GCM encryption thông tin bệnh nhân')),
                ('chief_complaint_blob', models.BinaryField(blank=True, help_text='Lý do khám đã mã hóa', null=True)),
                ('past_medical_history_blob', models.BinaryField(blank=True, help_text='Tiền sử bệnh đã mã hóa', null=True)),
                ('diagnosis_blob', models.BinaryField(blank=True, help_text='Chẩn đoán đã mã hóa', null=True)),
                ('status_blob', models.BinaryField(blank=True, help_text='Tình trạng hiện tại đã mã hóa', null=True)),
                ('medical_record_aes_key_blob', models.BinaryField(help_text='AES key cho hồ sơ y tế, đã mã hóa bằng CP-ABE Waters11')),
                ('medical_record_aes_iv_blob', models.BinaryField(help_text='IV cho AES-GCM encryption hồ sơ y tế')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Ngày tạo hồ sơ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(blank=True, help_text='User đã tạo dữ liệu y tế này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_medical_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dữ liệu y tế',
                'verbose_name_plural': 'Dữ liệu y tế',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_user', 'created_at'], name='backend_med_owner_u_667273_idx'), models.Index(fields=['patient_id'], name='backend_med_patient_6c48d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(help_text='Loại attribute', on_delete=django.db.models.deletion.CASCADE, related_name='users_with_attribute', to='backend.attribute')),
                ('user', models.ForeignKey(help_text='User sở hữu attribute này', on_delete=django.db.models.deletion.CASCADE, related_name='attributes_possessed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thuộc tính người dùng',
                'verbose_name_plural': 'Thuộc tính người dùng',
                'indexes': [models.Index(fields=['user', 'attribute'], name='backend_use_user_id_1cf67b_idx')],
                'unique_together': {('user', 'attribute')},
            },
        ),
    ]
