# Generated by Django 5.2.3 on 2025-06-14 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: ROLE:DOCTOR hoặc DEPARTMENT:CARDIO', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Thuộc tính CP-ABE',
                'verbose_name_plural': 'Các thuộc tính CP-ABE',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(blank=True, to='cpabe_service_app.attribute', verbose_name='Các thuộc tính được gán')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpabe_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng CP-ABE',
                'verbose_name_plural': 'Các hồ sơ người dùng CP-ABE',
            },
        ),
    ]
